In [43]:
import torch
x = torch.rand(2, 3, 4)  # A 3D tensor with shape (2, 3, 4)
print("Initial tensor:")
print(x)
print("Selecting elements:")
print(x[..., 2:])  # Selects the 3rd element (index 2) from the last dimension


Initial tensor:
tensor([[[0.8251, 0.2141, 0.7927, 0.0435],
         [0.9694, 0.4072, 0.9078, 0.3693],
         [0.4495, 0.8676, 0.4745, 0.8571]],

        [[0.8861, 0.4058, 0.0280, 0.4737],
         [0.7369, 0.5742, 0.8619, 0.9545],
         [0.4686, 0.0701, 0.5605, 0.1314]]])
Selecting elements:
tensor([[[0.7927, 0.0435],
         [0.9078, 0.3693],
         [0.4745, 0.8571]],

        [[0.0280, 0.4737],
         [0.8619, 0.9545],
         [0.5605, 0.1314]]])


In [37]:
x = torch.rand(3, 4)  
print("Initial tensor:")
print(x)
print("Selecting elements:")
print(x[..., 0]) 
print(x[2, ...]) 

Initial tensor:
tensor([[0.1664, 0.9387, 0.6266, 0.5383],
        [0.9255, 0.8432, 0.2640, 0.3603],
        [0.0766, 0.1742, 0.0799, 0.2729]])
Selecting elements:
tensor([0.1664, 0.9255, 0.0766])
tensor([0.0766, 0.1742, 0.0799, 0.2729])


In [ ]:
x = torch.rand(4)  
print("Initial tensor:")
print(x)
print("Selecting elements:")
print(x[..., 0])  

Initial tensor:
tensor([0.7836, 0.7017, 0.5609, 0.3930])
Selecting elements:
tensor(0.7836)


In [48]:
shifts_x = torch.arange(0, 7, dtype=torch.int32)* 1 / float(7)
print(shifts_x)

tensor([0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571])


In [49]:
shifts_x = torch.arange(0, 7, dtype=torch.int32) * 1 / float(7)
shifts_y = torch.arange(0, 7, dtype=torch.int32) * 1 / float(7)
shifts_y, shifts_x = torch.meshgrid(shifts_y, shifts_x, indexing="ij")
print(shifts_x)
print(shifts_y)

tensor([[0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
        [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
        [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
        [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
        [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
        [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571],
        [0.0000, 0.1429, 0.2857, 0.4286, 0.5714, 0.7143, 0.8571]])
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429],
        [0.2857, 0.2857, 0.2857, 0.2857, 0.2857, 0.2857, 0.2857],
        [0.4286, 0.4286, 0.4286, 0.4286, 0.4286, 0.4286, 0.4286],
        [0.5714, 0.5714, 0.5714, 0.5714, 0.5714, 0.5714, 0.5714],
        [0.7143, 0.7143, 0.7143, 0.7143, 0.7143, 0.7143, 0.7143],
        [0.8571, 0.8571, 0.8571, 0.8571, 0.8571, 0.8571, 0.8571]])
